package:
    name: "topaz"
    version: "0.0.0"

source:
    git_url: https://github.com/tbepler/topaz.git
    git_tag: v0.0.0

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - argparse #[py26]
        - numpy>=0.11
        - pandas
        - scikit-learn>=0.19.0
        - pillow
        - pytorch=0.2.0
        - torchvision


build:
    noarch: python
    number: 3
    script: "{{ PYTHON }} setup.py install --single-version-externally-managed --record=record.txt"


about:
    home: https://github.com/tbepler/topaz
    license: GPLv3
    license_file: LICENSE
