{% set data = load_setup_py_data() %}

package:
    name: "topaz"
    version: {{ data.get('version') }}

source:
    git_url: https://github.com/tbepler/topaz.git
    git_tag: v0.3.11 # Update to the latest release tag

channels:
  - conda-forge
  - defaults
channel_priority: strict

requirements:
    build:
        - python
        - setuptools
    run:
        - python>=3.8,<=3.13
        - future
        - numpy>=1.11
        - pandas>=0.20.3
        - scikit-learn>=0.19.0
        - scipy>=0.17.0
        - pillow>=6.2.0
        - pytorch>=1.0.0
        - torchvision
        - tqdm>=4.65.0
        - h5py>=3.7.0

build:
    noarch: python
    number: 0
    script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"


about:
    home: https://github.com/tbepler/topaz
    license: GPLv3
    license_file: LICENSE
