{% set data = load_setup_py_data() %}

package:
    name: "topaz"
    version: {{ data.get('version') }}

source:
    git_url: https://github.com/tbepler/topaz.git
    git_tag: master

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - argparse #[py26]
        - numpy>=0.11
        - pandas
        - scikit-learn>=0.19.0
        - pillow
        - pytorch>=1.0.0
        - torchvision


build:
    noarch: python
    number: 0
    script: "{{ PYTHON }} setup.py install --single-version-externally-managed --record=record.txt"


about:
    home: https://github.com/tbepler/topaz
    license: GPLv3
    license_file: LICENSE
